import libs = libensketch-geometry%lib{ensketch-geometry}
import libs += doctest%lib{doctest-main}

exe{libensketch-geometry-tests}: {hxx ixx txx cxx}{**} $libs
{
  test = true
}

out_pfx = [dir_path] $out_root/sources/
src_pfx = [dir_path] $src_root/sources/

cxx.poptions =+ "-I$out_pfx" "-I$src_pfx"
