intf_libs = # Interface dependencies.
import intf_libs += libensketch-xstd%lib{ensketch-xstd}
impl_libs = # Implementation dependencies.

lib{ensketch-geometry}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

# Build options.
#
out_pfx = [dir_path] $out_root/sources/
src_pfx = [dir_path] $src_root/sources/

cxx.poptions =+ "-I$out_pfx" "-I$src_pfx"

obja{*}: cxx.poptions += -DLIBENSKETCH_GEOMETRY_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBENSKETCH_GEOMETRY_SHARED_BUILD

# Export options.
#
lib{ensketch-geometry}:
{
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

liba{ensketch-geometry}: cxx.export.poptions += -DLIBENSKETCH_GEOMETRY_STATIC
libs{ensketch-geometry}: cxx.export.poptions += -DLIBENSKETCH_GEOMETRY_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{ensketch-geometry}: bin.lib.version = "-$version.project_id"
else
  lib{ensketch-geometry}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libensketch-geometry/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libensketch-geometry/
  install.subdirs = true
}
